---
- hosts: 003-SO-02.BSMYSZKOW.LOCAL
  tasks:
  - name: Install 7zip from a network share specifying the credentials
    win_package:
      path: \\dc01\MSI\adobe\AcroRdrDC1900820071_pl_PL.exe
      product_id: AcroRdrDC1900820071_pl_PL
      arguments: /S
      state: present
      
